name: Bug Report
description: Report a bug to help us improve Qragy
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: false
  - type: dropdown
    id: node-version
    attributes:
      label: Node.js version
      options:
        - "18"
        - "20"
        - "22"
        - Other
    validations:
      required: false
  - type: input
    id: qragy-version
    attributes:
      label: Qragy version
      placeholder: "e.g. 1.1.0"
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context, screenshots, or logs.
    validations:
      required: false
